### ISSUE TITLE
Исправить ссылку на базу GeoIP

### ISSUE THREAD

**Issue by skokhanovskiy** [merchantly/ansible#11]
Перестала работать ссылка на базу GeoIP, которая была добавлена в #10.
https://github.com/merchantly/ansible/blob/master/roles/geoip/defaults/main.yml

Сейчас ссылка отдает 404 Not Found. Необходимо указать ссылку на какой-то общий ресурс, где база GeoIP всегда будет доступна для всех.

**Comment by dapi** [comment]
Да, она была временная. Подумаю как это решить.

**Comment by dapi** [comment]
Добавил,  тут подробности - http://github.com/merchantly/doc/blob/master/ANALYTICS.md
