### ISSUE TITLE
внешние роли подключать через submodule

### ISSUE THREAD

**Issue by dapi** [merchantly/ansible#6]
Вместо `requirements.yml` внешние роли лучше подключать через submodule. Это дает возможность указать конкретный commit который используется в подключенном модуле и исключает ситуацию, когда через год подгружаются модули и они уже обновились и работают не ожидании образом.

Также это делает более однообразным использование собственных ролей в виде сабмодулей без публикации в galaxy.

**Comment by skokhanovskiy** [comment]
См. https://github.com/merchantly/ansible/pull/7#issuecomment-475513412

**Comment by dapi** [comment]
@skokhanovskiy Тебе нужно ссылки на коменты присылать или ты их уведомления получаешь? https://github.com/merchantly/ansible/pull/7#issuecomment-475664925

**Comment by skokhanovskiy** [comment]
Нет, не надо. Я получаю уведомления о коммитах.
